config/routes.rb
Rails.application.routes.draw do

  resources :tapes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tape.rb
class Tape < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  def index
    @tapes = Tape.all
  end

  def show
    @tape - Tape.find(params[:id])
  end

  def create
    @tape = Tape.create(tape_params)
    redirect_to tapes_url
  end

  def destroy
    puts "PARAMS ARE" + params.inspect
    @tape = Tape.find(params[:id])
    @tape.destroy
    redirect_to tapes_url
  end

    private

    def tape_params
      params.require(:tape).permit(:kind, :purpose)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tape_types_helper.rb
module TapeTypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllTheTape</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tapes/index.html.erb
<h1> All#the#Tapes! </h1>
<p>Find me in app/views/tapes/index.html.erb</p>

<%= form_for Tape.new do |t| %>
  <%= t.label :kind %>
  <%= t.text_field :kind %>
  <%= t.label :purpose %>
  <%= t.text_field :purpose %>
  <%= t.submit %>
<% end %>

  <% @tapes.each do |tape| %>
    <%= link_to tape.kind, tape_path(tape.id) %>
    <%= tape.purpose %>
    <br>
<% end %>

app/views/tapes/show.html.erb
<%= @tape.kind %>
<br>
<%= @user.purpose %>
<br>
<%= link_to("Delete Tape", tape(@tape.id), method: :delete)%>